
CFLAGS = -Wunused-variable -Wno-implicit-int -Wno-return-type -g -pedantic -ansi -Werror

all: 3-2 3-03

3-2: 3-2.c
	cc $(CFLAGS) 3-2.c -o 3-2

3-03: 3-03.c
	cc $(CFLAGS) 3-03.c -o 3-03

clean:
	rm -f 3-2 3-03

